//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BMS.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Web;

    public partial class Book
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Book()
        {
            book_image = "~/Images/Book/add.png";
            this.BorrowBooks = new HashSet<BorrowBook>();
        }
    
        public int book_id { get; set; }
        [Required(ErrorMessage = "Please enter book name.")]
        public string book_name { get; set; }
        public Nullable<int> book_category { get; set; }
        public Nullable<int> book_author { get; set; }
        public string book_image { get; set; }
        public string book_brief { get; set; }


        [NotMapped]
        public HttpPostedFileBase ImageUpload { get; set; }

        public virtual Author Author { get; set; }
        public virtual Category Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BorrowBook> BorrowBooks { get; set; }
    }
}
