//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BorrowBook
    {
        public int borrow_book_id { get; set; }
        public Nullable<int> admin_id { get; set; }
        public Nullable<int> borrower_id { get; set; }
        public Nullable<int> book_id { get; set; }
        public Nullable<int> category_id { get; set; }
        public Nullable<System.DateTime> borrow_date { get; set; }
        public Nullable<System.DateTime> expire_date { get; set; }
        public string status { get; set; }
    
        public virtual Admin Admin { get; set; }
        public virtual Book Book { get; set; }
        public virtual Category Category { get; set; }
        public virtual Borrower Borrower { get; set; }
    }
}
